# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sman
version:      1.01
version_from: Sman.pm
installdirs:  site
requires:
    Cache::Cache:                  0
    Cache::FileCache:              0
    Compress::Zlib:                0
    Digest::MD5:                   0
    File::Find:                    0
    File::Temp:                    0
    FindBin:                       0
    FreezeThaw:                    0
    POSIX:                         0
    Storable:                      0
    Term::Size:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
